apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  ports:
    - port: 8888
      name: jupyter
      targetPort: 8888
      protocol: TCP

  selector:
    app: combined
  type: LoadBalancer
